server:
  port: 8081
  servlet:
    context-path: /code

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.161:3306/ximalayaos_study?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: naliworld
    password: password!
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/
  security:
    user:
      name: admin
      password: admin